name: Code Review
description: Provide peer review feedback based on established HTML and CSS standards.
title: "CMPSC 302: Code Review"
body:
  - type: markdown
    attributes:
      value: |
        ## Code Review
  - type: markdown
    attributes:
      value: |
        Respond to the following areas of concerns for a basic HTML/CSS code review.
  - type: markdown
    attributes:
      value: |
        ### Assignment standards
  - type: dropdown
    attributes:
      label: This site has at least one page which is reviewable and publically availble at the reviewee's *.github.io URL.
      options:
        - "Yes"
        - "No"
    validations:
      required: true  
  - type: dropdown
    attributes:
      label: Reviewee's site implements at least `3` Astro components.
      options:
        - "Yes"
        - "No"
    validations:
      required: true 
  - type: dropdown
    attributes:
      label: Reviewee's site effectively implements a `BaseLayout` (or other similar construct) for controlling site-wide layout.
      options:
        - "Yes"
        - "No"
    validations:
      required: true 
  - type: dropdown
    attributes:
      label: Site being reviewed implements styles in the `public/style/style.css` file.
      options:
        - "Yes"
        - "No"
    validations:
      required: true 
  - type: markdown
    attributes:
      value: |
        ### HTML Standards
  - type: dropdown
    attributes:
      label: The sites's `BaseLayout` contains a `DOCTYPE` tag
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: dropdown
    attributes:
      label: The site's `BaseLayout` uses the `html` root element tag and specifies `en` as the page's language.
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: dropdown
    attributes:
      label: The sites's `BaseLayout` uses the `html` root element tag and specifies `en` as the page's language.
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Throughout all files, the site uses semantic elements where appropriate, only using `div` elements where semantic elements don't exist.
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Examples of improper use of non-semantic elements.
      description: In the text area below, provide references to the site's files that violate the "semantic element first" policy.
      value: |
        ```HTML
          <!-- Use code blocks to include examples -->
        ```
    validations:
      required: false
